"use client";
import { useCallback,useEffect,useState } from "react";
type Message={id:string;body:string;sender_id:string|null;message_kind:"participant"|"dibs_system"|"dibs_outbound";sender:{name:string}|null;created_at:string};
export function Chat({conversationId,userId,initialSignal,initialUserReported=false}:{conversationId:string;userId:string;initialSignal?:"possible"|"likely"|"confirmed";initialUserReported?:boolean}){
  const [messages,setMessages]=useState<Message[]>([]);const [signal,setSignal]=useState(initialSignal);const [userReported,setUserReported]=useState(initialUserReported);const [error,setError]=useState("");
  const load=useCallback(async()=>{const r=await fetch(`/api/conversations/${conversationId}/messages`);if(r.ok)setMessages((await r.json()).messages)},[conversationId]);
  useEffect(()=>{load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[load]);
  async function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const input=form.elements.namedItem("body") as HTMLInputElement;const body=input.value;input.value="";const r=await fetch(`/api/conversations/${conversationId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})});if(!r.ok)setError((await r.json()).error);await load()}
  async function report(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(`/api/conversations/${conversationId}/deal`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const data=await r.json();if(r.ok){setSignal(data.status);setUserReported(true)}else setError(data.error)}
  return <><div className="messages">{messages.length===0&&<p className="muted">Start the conversation. Messages refresh automatically.</p>}{messages.map(m=><div className={`bubble ${m.sender_id===userId?"mine":""}`} key={m.id}><small>{m.message_kind==="participant"?(m.sender?.name||"Participant"):"Dibs relay"}</small>{m.body}</div>)}</div><form className="chat-form" onSubmit={send}><input name="body" placeholder="Write a message..." required autoComplete="off"/><button>Send</button></form>{error&&<p className="error">{error}</p>}<div className="deal">{signal==="confirmed"||userReported?<div className="notice"><strong>{signal==="confirmed"?"Deal confirmed by both participants":"Your deal report was recorded"}</strong><br/>{signal==="confirmed"?"Matching buyer and seller reports created the confirmed deal.":"Confirmation waits for a matching report from the other participant."} Payment stays between buyer and seller.</div>:<form onSubmit={report}><strong>Think you reached a deal?</strong><p className="muted">Tell us what happened. One report is a signal, not automatic confirmation.</p><label>Agreed price</label><input name="price" type="number" min="1" step="0.01" required/><label>What happened?</label><input name="evidence" placeholder="we agreed and set a pickup time" required maxLength={500}/><p><button className="purple">Record signal</button></p></form>}</div></>}